name: Cargo version
description: Get the version from Cargo.toml.

outputs:
  version:
    description: Cargo version.
    value: ${{ steps.cargo.outputs.version }}

runs:
  using: composite
  steps:
    - name: Cargo version
      id: cargo
      shell: bash
      run: |
        version=$(grep '^version =' Cargo.toml | head -n 1 | sed 's/.*"\(.*\)"/\1/')
        echo "version=$version" >> $GITHUB_OUTPUT
