name: Cargo version
description: Get the version from Cargo.toml.

inputs:
  increment:
    description: |
      The version number or one of 'none', 'major', 'minor', 'patch'. 
      If 'none', the current version is returned.
    default: none

outputs:
  version:
    description: Cargo version
    value: ${{ steps.current.outputs.version }}

runs:
  using: composite
  steps:
    - name: Increment version
      if: ${{ inputs.increment != 'none' }}
      id: increment
      shell: bash
      run: |
        current=$(grep '^version =' Cargo.toml | head -n 1 | sed 's/.*"\(.*\)"/\1/')
        case "${{ inputs.increment }}" in
          major)
            IFS='.' read -r major minor patch <<< "$current"
            incremented="$((major + 1)).0.0"
            ;;
          minor)
            IFS='.' read -r major minor patch <<< "$current"
            incremented="$major.$((minor + 1)).0"
            ;;
          patch)
            IFS='.' read -r major minor patch <<< "$current"
            incremented="$major.$minor.$((patch + 1))"
            ;;
          *)
            incremented="${{ inputs.increment }}"
            ;;
        esac

        sed -i -E "s/^version = .*/version = \"$incremented\"/1" Cargo.toml
        git commit -am "Increment Cargo version to $incremented"

    - name: Read version
      id: current
      shell: bash
      run: |
        version=$(grep '^version =' Cargo.toml | head -n 1 | sed 's/.*"\(.*\)"/\1/')
        echo "version=$version" >> $GITHUB_OUTPUT