name: Find latest release
description: Find the latest release branch and version.

outputs:
  version:
    description: Version of the release.
    value: ${{ steps.latest.outputs.version }}
  branch:
    description: Name of the release branch.
    value: ${{ steps.latest.outputs.branch }}

runs:
  using: composite
  steps:
    - name: Latest release
      id: latest
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        set -ex
        # git fetch origin
        rustc .github/scripts/release-branch.rs -o /tmp/release-branch
        version=`/tmp/release-branch`

        echo "branch=release-$version" >> $GITHUB_OUTPUT
        echo "version=$version" >> $GITHUB_OUTPUT
