name: Git identity
description: Set Git identity for the workflow.

outputs:
  cache-hit:
    description: Whether the cache was hit
    value: ${{ steps.cache.outputs.cache-hit }}

runs:
  using: composite
  steps:
    - uses: actions/cache@v4
      id: cache
      with:
        path: |
          ~/.cargo/
          target/
        key: cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          cargo-${{ hashFiles('**/Cargo.lock') }}
          cargo-
