name: Git identity
description: Set Git identity for the workflow.

runs:
  using: composite
  steps:
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo
          target
        key: cargo-${{ hashFiles('Cargo.lock') }}
        restore-keys: |
          cargo-${{ hashFiles('Cargo.lock') }}
          cargo-