[package]
name = "credibil-ci"
edition.workspace = true

[lints]
workspace = true

[[bin]]
name = "calculate-version"
path = "src/calculate-version.rs"

[dependencies]
anyhow.workspace = true
cargo-semver-checks = "0.43.0"
