name: Prepare release notes
description: Prepare release notes for the upcoming release

inputs:
  version:
    description: The version to use to create release notes.
    required: true
  branch:
    description: The branch to push the updated release notes to.
    required: true

# git reset --hard origin/${{ steps.latest.outputs.branch }}
runs:
  using: composite
  steps:
    - name: Archive previous release
      shell: bash
      run: |
        set -ex

        title=$(sed -n '1p' RELEASES.md)
        version=$(echo $title | sed 's/## //')
        version_x=$(echo $version | sed 's/.$/x/')
        sed -i "/ARCHIVE_START/a * [$version_x](https://github.com/${{ github.repository }}/blob/release-$version/RELEASES.md)" RELEASES.md

    - name: Generate Release Notes
      id: notes
      uses: RedCrafter07/release-notes-action@v1
      with:
        tag-name: ${{ github.event.inputs.tag-name }}
        # token: ${{ secrets.GITHUB_TOKEN }}

    - name: Create next release notes
      shell: bash
      run: |
        set -ex
        sed -i '0,/---/d' RELEASES.md
        archive=$(cat RELEASES.md)

        cat > RELEASES.md <<EOF
        ## ${{ inputs.version }}

        Unreleased

        ### Added

        ### Changed

        ${{ steps.notes.outputs.release-notes }}

        ---
        $archive
        EOF

        git commit -am "Update release notes for ${{ inputs.version }}"
        git push origin HEAD:${{ inputs.branch }}
