name: Audit

on:
  workflow_call:

permissions:
  contents: read

jobs:
  security_audit:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v5
        
      - uses: credibil/pipeline/.github/actions/cargo-cache@main

      - uses: rustsec/audit-check@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
