# Reusable verification workflow for Rust 
# https://docs.github.com/en/actions/how-tos/reuse-automations/reuse-workflows

name: Release

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
        description: The new version to set.

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
permissions:
  contents: write
env:
  RUSTFLAGS: -Dwarnings

jobs:
  version:
    name: Set version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-release

      - run: |
          sudo apt-get update
          sudo apt-get -y install libwebkit2gtk-4.1-dev

      - name: Release
        run: cargo release version ${{ inputs.version }} --execute --no-confirm

      - name: Commit 
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email '<>'
          # git commit -am "update version"
          git commit -C HEAD@{1}
          git push --force
