# Reusable verification workflow for Rust 
# https://docs.github.com/en/actions/how-tos/reuse-automations/reuse-workflows

name: Release

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
        description: The new version to set.

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
permissions:
  contents: write
env:
  RUSTFLAGS: -Dwarnings

jobs:
  version:
    name: Set version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-release
      - run: |
          sudo apt-get update
          sudo apt-get -y install libwebkit2gtk-4.1-dev
      - run: cargo release version ${{ inputs.version }} --execute --no-confirm


