# Reusable verification workflow for Rust 
# https://docs.github.com/en/actions/how-tos/reuse-automations/reuse-workflows

name: Release

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
        description: The new version to set.

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
permissions:
  contents: write
env:
  RUSTFLAGS: -Dwarnings

jobs:
  version:
    name: Set version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-release
      - name: Release
        run: cargo release version ${{ inputs.version }} --execute --no-confirm

      - name: Commit 
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
          git commit -am "update version"
          git push origin HEAD:main --force
