# Reusable verification workflow for Rust 
# https://docs.github.com/en/actions/how-tos/reuse-automations/reuse-workflows

name: Rust CI

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
        description: The new version to set.

jobs:
  version:
    name: Set version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      # - uses: dtolnay/install@cargo-outdated
      - uses: dtolnay/install@cargo-release
      - run: |
          sudo apt-get update
          sudo apt-get -y install libwebkit2gtk-4.1-dev
      - run: cargo release version ${{ inputs.version }} --execute --no-confirm


